### ISSUE TITLE
Command Regrouping

### ISSUE THREAD

**Issue by zmmille2** [projector-cli/projector-cli#5]
Today, projector's grouping of commands is confusing.

- `pjr`
  - `version`
  - `agile`
    - `sprints`
      - `create`
    - `project`
      - `create`
      - `delete`
    - `work`
      - `create`
      - `import`
      - `template`
        - `init`
        - `list`
  - `links`
    - `snowball`
    - `playbook`
    - `playbook-issues`
  - `playbook`
    - `issues`
      - `create`
      - `open`
    - `template`
      - `init`
      - `list`
  - `repo`
    - `create`

The issues are as follows:
1. Clarity between source and target is lacking.
  A. `pjr playbook template list` and `pjr agile work template list` could be mistaken for each other.
  B. `pjr agile work import`, `pjr agile work template init`, and `pjr playbook template init` all deal with template initialization, but they could likely be reorganized to emphasize source and target.
2. Links may be irrelevant. Links should be managed and dynamically discovered by the user, with some defaults if we are keen.
3. Changing projects is cumbersome. To target a different playbook or project, you'd have to reconfigure projector to point to the new project. This is something we should manage.
4. Just because we can, doesn't mean we should.
    A. Projector is a tool to bootstrap projects, we should drop link and repo creation.
    B. We shouldn't try to compete on creation of new templates: Word editors are much better here.
    C. Creation of projects and repos is probably better done in the tools themselves.

I propose the following command structure:
- `pjr`
  - `version`: Displays the current version of projector.
  - `status`: Show which playbooks and projects are known, and which are selected.
  - `playbook`
    - `status`: Show which playbooks are known, and which are selected.
    - `list`: Same as status.
    - `select`: Select a playbook. Optionally exclusively select a playbook.
    - `deselect`: Deselect a playbook.
    - `add`: Add a playbook to the list of known playbooks.
    - `remove`: Remove a playbook from the list of known playbooks.
    - `templates`: List templates from selected playbooks. Support for name or path filtering. Supports instructions file for consumption by `pjr project work deploy`
  - `project`
    - `status`: Show which projects are known, and which are selected.
    - `list`: Same as status.
    - `select`: Select a project. Optionally exclusively select a project.
    - `deselect`: Deselect a project.
    - `add`: Add a project to the list of known projects.
    - `remove`: Remove a project from the list of known projects.
    - `work`
      - `sprints`: Create sprints.
      - `deploy`: Deploys templates from playbooks into a project or projects.

**Comment by zmmille2** [comment]
Furthermore, ideally, we wouldn't download files to the local system at all - instead, we can work with objects in memory. This refactor would likely remove the object service.

**Comment by elizabethhalper** [comment]
I like this a lot! Great job thinking through the user flow & experience (especially love point #4). My below comment is more of a "thinking-out-loud" type of thing and I'm totally fine not doing anything about it.

The only one I'm a little iffy about is the `work` sub-command. I think its okay for now, and the actions are similar so are good to group together, but eventually a user may want to edit sprints, and it might be more user friendly to say something like `pjr project deploy template` depending on how those two commands are interwoven (I'd need to refresh my knowledge of how that works).

**Comment by zmmille2** [comment]
Sounds good - so we'll do 
...
* sprints
  * create, etc...
* template
  * deploy, etc...
...

**Comment by zmmille2** [comment]
Related to #22
